// This file is generated by npm run build:icons

export type IconName =
	| "audio-lines"
	| "chart"
	| "check"
	| "checked-box"
	| "chevron-right"
	| "clipboard"
	| "close"
	| "lightbulb"
	| "minus"
	| "plus"
	| "question"
	| "sun"
	| "unchecked-box"
	| "webcam";
